---

- name: "Testing Filters"
  hosts: R1
  tasks:
  - name: "Testingt some Filters"
    vars:
      uk_prefixes:
        - "10.0.0.0/24"
        - "2.2.2.2/32"
        - "192.168.8.0/24"
      us_prefixes:
        - "10.0.0.0/24"
        - "1.1.1.1/32"
        - "192.168.8.0/24"
    debug:
      msg: "{{ uk_prefixes | difference(us_prefixes) }}"