---

- name: "Testing J2 Templates"
  hosts: R1_2
  gather_facts: false
  connection: network_cli

  tasks:
  - name: "BGP CONFIG"
    cisco.ios.ios_config:
      src: bgp.j2
    register: out

  - debug:
        msg: "{{ out }}"