---

- name: "Configuration of VLANs via Jinja2"
  connection: network_cli
  hosts: cisco-sw

  tasks:

  - name: "Pushing CLI commands"
    cisco.ios.ios_config:
      src: "{{ansible_network_os}}-vlan.j2"
    register: ios_output
  
  - name: "Printing Output"
    debug:
      msg: "{{ ios_output }}"