---
# tasks file for role_eigrp

- name: "TASK 1 - {{ TASK_ONE_NAME }}"
  cisco.ios.ios_config:
    src: "{{ EIGRP_TEMPLATE }}"
  register: eigrp_output

- name: "TASK 2 -  {{ TASK_TWO_NAME }}"
  debug:
    msg: "{{ eigrp_output.commands }}"

- name: "TASK 3 - {{ TASK_THREE_NAME }}"
  cisco.ios.ios_command:
    commands:
      - "show running-config | section eigrp"
  register: show_output

- name: "TASK 4 - {{ TASK_FOUR_NAME }}"
  debug:
    msg: "{{ show_output.stdout_lines }}"