---
BGP:
  ASN: "65001"
  peers:
    - neighbor: "10.0.0.2"
      peer_asn: "65002"

    - neighbor: "10.0.0.13"
      peer_asn: "13"

eigrp:
  asn: "1"
  rid: "1.1.1.1"
  networks:
    - "10.0.0.0 0.0.0.255"
    - "192.168.0.0 0.0.0.255"
    - "1.1.1.1 0.0.0.0"

loopback:
  address: "1.1.1.1"
  subnet: "255.255.255.255"

ntp:
  servers:
    - "1.1.1.1"
    - "2.2.2.2"
    - "3.3.3.3"
    - "4.4.4.4"
    - "5.5.5.5"

ospf:
  rid: "1.1.1.1"
  networks:
    - address: "10.1.2.0"
      wildcard: "0.0.0.255"
      area: "0"
  default_originate: true

bgp:
  rid: "1.1.1.1"
  asn: "1"
  neighbors:
    - address: "10.1.2.2"
      peer_asn: "2"
  networks:
    - address: "88.88.88.88"
      mask: "255.255.255.255"

    - address: "100.100.100.100"
      mask: "255.255.255.255"