---
BGP:
  ASN: "65002"
  peers:
    - neighbor: "10.0.0.1"
      peer_asn: "65001"

    - neighbor: "10.0.0.23"
      peer_asn: "23"

eigrp_style: "normal"
eigrp:
  asn: "2"

loopback:
  address: "2.2.2.2"
  subnet: "255.255.255.255"

ospf:
  rid: "2.2.2.2"
  networks:
    - address: "10.1.2.0"
      wildcard: "0.0.0.255"
      area: "0"
    - address: "10.2.3.0"
      wildcard: "0.0.0.255"
      area: "0"
    - address: "10.2.4.0"
      wildcard: "0.0.0.255"
      area: "0"
  default_originate: false



bgp:
  rid: "2.2.2.2"
  asn: "2"
  neighbors:
    - address: "10.1.2.1"
      peer_asn: "1"
    - address: "10.2.3.3"
      peer_asn: "3"
    - address: "10.2.4.4"
      peer_asn: "4"